"""empty message

Revision ID: 030ef017a117
Revises: 
Create Date: 2020-05-31 16:23:32.135474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030ef017a117'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('about', sa.String(length=1020), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('tutors')
    # ### end Alembic commands ###
