"""empty message

Revision ID: 4fee434d949a
Revises: 88e0f36b9721
Create Date: 2020-05-31 23:00:52.600852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fee434d949a'
down_revision = '88e0f36b9721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bookings', 'student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('applications')
    # ### end Alembic commands ###
