"""empty message

Revision ID: 560c5ce255f0
Revises: 030ef017a117
Create Date: 2020-05-31 17:06:07.528087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560c5ce255f0'
down_revision = '030ef017a117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('free', sa.JSON(), nullable=True))
    op.add_column('tutors', sa.Column('goals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'goals')
    op.drop_column('tutors', 'free')
    # ### end Alembic commands ###
