"""empty message

Revision ID: 7a904b5361a3
Revises: 7fc00ac32eca
Create Date: 2020-05-31 22:44:11.047423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a904b5361a3'
down_revision = '7fc00ac32eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bookings', 'student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('applications')
    # ### end Alembic commands ###
