"""empty message

Revision ID: 7fc00ac32eca
Revises: 560c5ce255f0
Create Date: 2020-05-31 17:26:56.202069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc00ac32eca'
down_revision = '560c5ce255f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('day_of_week', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'time')
    op.drop_column('bookings', 'day_of_week')
    # ### end Alembic commands ###
